---
title: Schisto IBM 
author: |
 | Matthew Malishev^1^* and David J Civitello^1^    
 |  
 | _^1^ Department of Biology, Emory University, 1510 Clifton Road NE, Atlanta, GA, USA, 30322_
#bibliography:/Users/malishev/Documents/Melbourne Uni/Thesis_2016/library.bib
fontsize: 10
geometry: margin=1in
documentclass: article
linkcolor: pink
urlcolor: blue
citecolor: red
output:
  html_document:
    highlight: tango
    code_folding: hide
    toc: yes
    toc_depth: 4
    number_sections: no
    toc_float: yes
  pdf_document:
    includes:
      in_header: # add .tex file with header content
    highlight: tango
    template: null
    toc: yes
    toc_depth: 4
    number_sections: false
    fig_width: 4
    fig_height: 5
    fig_caption: true
    df_print: tibble 
    citation_package: biblatex # natbib
    latex_engine: xelatex #pdflatex # lualatex
    keep_tex: true # keep .tex file in dir 
  word_document:
    highlight: tango
    keep_md: yes
    pandoc_args: --smart
    #reference: mystyles.docx
    toc: yes
inludes:
  before_body: before_body.tex
subtitle: 
tags:
- nothing
- nothingness
params: 
  dir: "/Users/malishev/Documents/Emory/research/schisto_ibm"
  date: !r Sys.Date()
  version: !r getRversion()
  email: "matthew.malishev@gmail.com"
  doi: https://github.com/darwinanddavis/SchistoIBM
classoption: portrait
# ^['https://github.com/darwinanddavis/SchistoIBM'] # footnote
vignette: >
  %\VignetteIndexEntry{Schisto IBM}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "all"} } });
</script>

##### 

```{r echo = FALSE}
# packages <- c("knitr", "rmarkdown")
# lapply(packages,library,character.only=T)
```

Date: `r params$date`  
R version: `r params$version`  
*Corresponding author: `r params$email`

Model from [Civitello et al 2018 Bioenergetic theory predicts infection dynamics of human schistosomes in intermediate host snails across ecological gradients](https://onlinelibrary.wiley.com/doi/abs/10.1111/ele.12937)  

\newpage  

## Overview  

IBM of snail and schistosome ecology, including resources and environmental temperature, driven by energetic consequences.  

Population model of individual hosts (snails) and parasites (schistosomes) in a lake system. Host and parasite population sizes and production of different parasite life stages are driven by a population model. Parasites are released into the habitat according to reproduction rules of a full energy and mass budget model based on Dynamic Energy Budget (DEB) theory. Hosts feed on resource patches in the habitat and are exposed to schistosomes depending on the type of resource patch they feed on.  

The host population is size and age structured, where parasite loading varies depending on the biomass of the host. Host biomass, including energy reserves, maintenance, and reproductive potential, is modelling through a DEB model.    

The energetics model determines the intake and production of parasites. The simulation runs over a year and emulates a lake system in Kenya where schistosomes are found.   

The energy reserves, somatic maintenance, and growth of hosts. The reproductive capacity of hosts is the parasite biomass prodcuted.  

\newpage  

## Environment  
### Resources  
$$
\frac
{dR}
{dt}
= r
  \left(
  1-\frac{R}{K}
  \right)
  R -
  \sum -i_{M}L^{2}f_{H}
$$
\  
$\sum -i_{M}L^{2}f_{H}$ = feeding by snails  

### Miracidia  

$$
\frac
{dM}
{dt}
= M(t)
- \sum uptake 
- death
$$
\  
$M(t)$ = miracidia in environment  
$\sum uptake$ = infection of hosts by miracidia. **Not a DEB parameter**   

### Cercariae    

$$
\frac
{dC}
{dt}
= \sum \frac{dRp}{dt} 
- death
$$
\   
$\sum \frac{dRp}{dt}$ = cumulative release of cercariae (parasite reproduction)

\newpage  

## Individual  

### Host 

#### Host length 

$$
  \frac 
    {d L}
    {d t}
    = \frac
      {gY_{VE}}
      {3\chi} 
        \cdot \left( \frac 
        {\kappa^{*} a_{M}e - (m_{V} + m_{R}E_{M}\delta)\chi L}
        {e + g}
        \right)
$$

#### Host reserve

$$
  \frac 
    {d e}
    {d t}
    = (f_{H} - e)
    \frac
      {a_{M}}
      {\chi E_{M}L} - p
        \left(
        \frac 
        {i_{PM}f_{P}}
        {E_{M}}
        \right)
$$

#### Host development (maturity)

$$
  \frac
  {d D}
  {d t}
  = \begin{cases}
      \text{if} \ D < D_{R}, & (1 - \kappa^{*})C - m_{D}D \\
      \text{if} \ D ≥ D_{R}, & 0
    \end{cases}
$$

#### Host reproduction

$$
  \frac
  {d R_{H}}
  {d t}
  = \begin{cases}
      \text{if} \ D < D_{R}, & 0 \\
      \text{if} \ D ≥ D_{R}, & (1 - \kappa^{*})C - m_{D}D
    \end{cases}
$$
  
### Parasite  

#### Parasite biomass (growth)  

$$
  \frac
  {d P}
  {d t}
  = P(Y_{PE}i_{PM}f_{P} (1-r_{P}) -m_{P})
$$

#### Parasite reproduction
$$
  \frac
  {d R_{P}}
  {d t}
  = \gamma_{RP}Y_{PE}i_{PM}f_{P}r_{P}
$$

#### Damage density
$$
  \frac 
    {d \delta}
    {d t}
    = \frac
      {\Theta} 
      {\chi L^{3}} 
      \cdot \frac
      {dR_{P}}
      {dt}
        + k_{R}(1-e)-k_{R}\delta-
        \frac
          {3\delta}
          {L}
          \cdot \frac 
            {dL}
            {dt}
$$
\  
$\frac {3\delta}{L}\cdot \frac {dL}{dt}$ = growth dilution. Growth of host reduces damage density      
$\frac {\Theta} {\chi L^{3}}$ = damage intensity   
$k_{R}$ = damage repair rate (via reserve depletion)  
  
#### Cumulative hazard for host
$$
  \frac
  {d H}
  {d t}
  = h_{b}+h_{\delta} \ max(\delta - \delta_{0}, \ 0)
$$
\  
$\delta_{0}$ = linear damage density function      
$h_{b}$ = background hazard rate  
$h_{\delta}$ = hazard coefficient    

\newpage  

## References

[Civitello et al 2018 Bioenergetic theory predicts infection dynamics of human schistosomes in intermediate host snails across ecological gradients](https://onlinelibrary.wiley.com/doi/abs/10.1111/ele.12937)  

